SUPPORTED_IMAGE_EXTENSIONS = (".jpg", ".jpeg")

POSITIVE_BINARY_LABEL = "moth"
NEGATIVE_BINARY_LABEL = "nonmoth"
NULL_DETECTION_LABELS = [NEGATIVE_BINARY_LABEL]

POSITIVE_COLOR = [0, 100 / 255, 1, 0.8]  # Blue
# NEGATIVE_COLOR = [1, 0, 162 / 255, 1]  # Pink
NEUTRAL_COLOR = [1, 1, 1, 0.5]  # White
NEGATIVE_COLOR = NEUTRAL_COLOR
