"""Init existing tables

Revision ID: 3665528a445c
Revises: 
Create Date: 2023-03-08 15:31:32.710819

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3665528a445c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
