"""add fields for tracking

Revision ID: 90d5f6ae09ec
Revises: 3665528a445c
Create Date: 2023-03-08 16:53:32.671117

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "90d5f6ae09ec"
down_revision = "3665528a445c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "detections",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "detections",
        sa.Column("source_image_width", sa.Integer(), nullable=True),
    )
    op.add_column(
        "detections",
        sa.Column("source_image_height", sa.Integer(), nullable=True),
    )
    op.add_column(
        "detections",
        sa.Column("source_image_previous_frame", sa.Integer(), nullable=True),
    )
    op.add_column(
        "detections",
        sa.Column("sequence_id", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "detections", sa.Column("sequence_frame", sa.Integer(), nullable=True)
    )
    op.add_column(
        "detections",
        sa.Column("sequence_previous_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "detections",
        sa.Column("sequence_previous_cost", sa.Float(), nullable=True),
    )
    op.add_column("detections", sa.Column("cnn_features", sa.JSON(), nullable=True))
    op.add_column("images", sa.Column("width", sa.Integer(), nullable=True))
    op.add_column("images", sa.Column("height", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "height")
    op.drop_column("images", "width")
    op.drop_column("detections", "cnn_features")
    op.drop_column("detections", "sequence_previous_cost")
    op.drop_column("detections", "sequence_previous_id")
    op.drop_column("detections", "sequence_frame")
    op.drop_column("detections", "sequence_id")
    op.drop_column("detections", "source_image_previous_frame")
    op.drop_column("detections", "source_image_height")
    op.drop_column("detections", "source_image_width")
    op.drop_column("detections", "timestamp")
    # ### end Alembic commands ###
