"""New column for saving logits to detections

Revision ID: 68f8b8fe793a
Revises: 1544478c3031
Create Date: 2025-08-07 15:50:24.447765

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "68f8b8fe793a"
down_revision = "1544478c3031"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("detections", sa.Column("logits", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("detections", "logits")
    # ### end Alembic commands ###
